#ifndef ACCELSEARCH_CMD_H
#define ACCELSEARCH_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -ncpus: Number of processors to use with OpenMP */
  int ncpusP;
  int ncpus;
  int ncpusC;
  /***** -lobin: The first Fourier frequency in the data file */
  int lobinP;
  int lobin;
  int lobinC;
  /***** -numharm: The number of harmonics to sum (power-of-two) */
  int numharmP;
  int numharm;
  int numharmC;
  /***** -zmax: The max (+ and -) Fourier freq deriv to search */
  int zmaxP;
  int zmax;
  int zmaxC;
  /***** -wmax: The max (+ and -) Fourier freq double derivs to search */
  int wmaxP;
  int wmax;
  int wmaxC;
  /***** -sigma: Cutoff sigma for choosing candidates */
  int sigmaP;
  float sigma;
  int sigmaC;
  /***** -rlo: The lowest Fourier frequency (of the highest harmonic!) to search */
  int rloP;
  double rlo;
  int rloC;
  /***** -rhi: The highest Fourier frequency (of the highest harmonic!) to search */
  int rhiP;
  double rhi;
  int rhiC;
  /***** -flo: The lowest frequency (Hz) (of the highest harmonic!) to search */
  int floP;
  double flo;
  int floC;
  /***** -fhi: The highest frequency (Hz) (of the highest harmonic!) to search */
  int fhiP;
  double fhi;
  int fhiC;
  /***** -inmem: Compute full f-fdot plane in memory.  Very fast, but only for short time series. */
  int inmemP;
  /***** -photon: Data is poissonian so use freq 0 as power normalization */
  int photonP;
  /***** -median: Use block-median power normalization (default) */
  int medianP;
  /***** -locpow: Use double-tophat local-power normalization (not usually recommended) */
  int locpowP;
  /***** -zaplist: A file of freqs+widths to zap from the FFT (only if the input file is a *.[s]dat file) */
  int zaplistP;
  char *zaplist;
  int zaplistC;
  /***** -baryv: The radial velocity component (v/c) towards the target during the obs */
  int baryvP;
  double baryv;
  int baryvC;
  /***** -otheropt: Use the alternative optimization (for testing/debugging) */
  int otheroptP;
  /***** -noharmpolish: Do not use 'harmpolish' by default */
  int noharmpolishP;
  /***** -noharmremove: Do not remove harmonically related candidates (never removed for numharm = 1) */
  int noharmremoveP;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* ACCELSEARCH_CMD_H */
