#ifndef BINCAND_CMD_H
#define BINCAND_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -plo: The low pulsar period to check (s) */
  int ploP;
  double plo;
  int ploC;
  /***** -phi: The high pulsar period to check (s) */
  int phiP;
  double phi;
  int phiC;
  /***** -rlo: The low Fourier frequency bin to check */
  int rloP;
  double rlo;
  int rloC;
  /***** -rhi: The high Fourier frequency bin to check */
  int rhiP;
  double rhi;
  int rhiC;
  /***** -psr: Name of pulsar to check for (do not include J or B) */
  int psrnameP;
  char *psrname;
  int psrnameC;
  /***** -candnum: Number of the candidate to optimize from candfile. */
  int candnumP;
  int candnum;
  int candnumC;
  /***** -candfile: Name of the bincary candidate file. */
  int candfileP;
  char *candfile;
  int candfileC;
  /***** -usr: Describe your own binary candidate.  Must include all of the following (assumed) parameters */
  int usrP;
  /***** -pb: The orbital period (s) */
  int pbP;
  double pb;
  int pbC;
  /***** -x: The projected orbital semi-major axis (lt-sec) */
  int asinicP;
  double asinic;
  int asinicC;
  /***** -e: The orbital eccentricity */
  int eP;
  double e;
  int eC;
  /***** -To: The time of periastron passage (MJD) */
  int ToP;
  double To;
  int ToC;
  /***** -w: Longitude of periastron (deg) */
  int wP;
  double w;
  int wC;
  /***** -wdot: Rate of advance of periastron (deg/yr) */
  int wdotP;
  double wdot;
  int wdotC;
  /***** -mak: Determine optimization parameters from 'infile.mak' */
  int makefileP;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* BINCAND_CMD_H */
