#ifndef PREPDATA_CMD_H
#define PREPDATA_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -ncpus: Number of processors to use with OpenMP */
  int ncpusP;
  int ncpus;
  int ncpusC;
  /***** -o: Root of the output file names */
  int outfileP;
  char *outfile;
  int outfileC;
  /***** -filterbank: Raw data in SIGPROC filterbank format */
  int filterbankP;
  /***** -psrfits: Raw data in PSRFITS format */
  int psrfitsP;
  /***** -noweights: Do not apply PSRFITS weights */
  int noweightsP;
  /***** -noscales: Do not apply PSRFITS scales */
  int noscalesP;
  /***** -nooffsets: Do not apply PSRFITS offsets */
  int nooffsetsP;
  /***** -window: Window correlator lags with a Hamming window before FFTing */
  int windowP;
  /***** -if: A specific IF to use if available (summed IFs is the default) */
  int ifsP;
  int ifs;
  int ifsC;
  /***** -clip: Time-domain sigma to use for clipping (0.0 = no clipping, 6.0 = default */
  int clipP;
  float clip;
  int clipC;
  /***** -noclip: Do not clip the data.  (The default is to _always_ clip!) */
  int noclipP;
  /***** -invert: For rawdata, flip (or invert) the band */
  int invertP;
  /***** -zerodm: Subtract the mean of all channels from each sample (i.e. remove zero DM) */
  int zerodmP;
  /***** -nobary: Do not barycenter the data */
  int nobaryP;
  /***** -shorts: Use short ints for the output data instead of floats */
  int shortsP;
  /***** -numout: Output this many values.  If there are not enough values in the original data file, will pad the output file with the average value */
  int numoutP;
  long numout;
  int numoutC;
  /***** -downsamp: The number of neighboring bins to co-add */
  int downsampP;
  int downsamp;
  int downsampC;
  /***** -offset: Number of spectra to offset into as starting data point */
  int offsetP;
  long offset;
  int offsetC;
  /***** -start: Starting point of the processing as a fraction of the full obs */
  int startP;
  double start;
  int startC;
  /***** -dm: The dispersion measure to de-disperse (cm^-3 pc) */
  int dmP;
  double dm;
  int dmC;
  /***** -mask: File containing masking information to use */
  int maskfileP;
  char *maskfile;
  int maskfileC;
  /***** -ignorechan: Comma separated string (no spaces!) of channels to ignore (or file containing such string).  Ranges are specified by min:max[:step] */
  int ignorechanstrP;
  char *ignorechanstr;
  int ignorechanstrC;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* PREPDATA_CMD_H */
