#ifndef PREPSUBBAND_CMD_H
#define PREPSUBBAND_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -ncpus: Number of processors to use with OpenMP */
  int ncpusP;
  int ncpus;
  int ncpusC;
  /***** -o: Root of the output file names */
  int outfileP;
  char *outfile;
  int outfileC;
  /***** -filterbank: Raw data in SIGPROC filterbank format */
  int filterbankP;
  /***** -psrfits: Raw data in PSRFITS format */
  int psrfitsP;
  /***** -noweights: Do not apply PSRFITS weights */
  int noweightsP;
  /***** -noscales: Do not apply PSRFITS scales */
  int noscalesP;
  /***** -nooffsets: Do not apply PSRFITS offsets */
  int nooffsetsP;
  /***** -wapp: Raw data in Wideband Arecibo Pulsar Processor (WAPP) format */
  int wappP;
  /***** -window: Window correlator lags with a Hamming window before FFTing */
  int windowP;
  /***** -numwapps: Number of WAPPs used with contiguous frequencies */
  int numwappsP;
  int numwapps;
  int numwappsC;
  /***** -if: A specific IF to use if available (summed IFs is the default) */
  int ifsP;
  int ifs;
  int ifsC;
  /***** -clip: Time-domain sigma to use for clipping (0.0 = no clipping, 6.0 = default */
  int clipP;
  float clip;
  int clipC;
  /***** -noclip: Do not clip the data.  (The default is to _always_ clip!) */
  int noclipP;
  /***** -invert: For rawdata, flip (or invert) the band */
  int invertP;
  /***** -zerodm: Subtract the mean of all channels from each sample (i.e. remove zero DM) */
  int zerodmP;
  /***** -runavg: Running mean subtraction from the input data */
  int runavgP;
  /***** -sub: Write subbands instead of de-dispersed data */
  int subP;
  /***** -subdm: The DM to use when de-dispersing subbands for -sub */
  int subdmP;
  double subdm;
  int subdmC;
  /***** -numout: Output this many values.  If there are not enough values in the original data file, will pad the output file with the average value */
  int numoutP;
  long numout;
  int numoutC;
  /***** -nobary: Do not barycenter the data */
  int nobaryP;
  /***** -offset: Number of spectra to offset into as starting data point */
  int offsetP;
  long offset;
  int offsetC;
  /***** -start: Starting point of the processing as a fraction of the full obs */
  int startP;
  double start;
  int startC;
  /***** -lodm: The lowest dispersion measure to de-disperse (cm^-3 pc) */
  int lodmP;
  double lodm;
  int lodmC;
  /***** -dmstep: The stepsize in dispersion measure to use(cm^-3 pc) */
  int dmstepP;
  double dmstep;
  int dmstepC;
  /***** -numdms: The number of DMs to de-disperse */
  int numdmsP;
  int numdms;
  int numdmsC;
  /***** -nsub: The number of sub-bands to use */
  int nsubP;
  int nsub;
  int nsubC;
  /***** -downsamp: The number of neighboring bins to co-add */
  int downsampP;
  int downsamp;
  int downsampC;
  /***** -dmprec: The number of decimals in the precision of the DM in the filename. */
  int dmprecP;
  int dmprec;
  int dmprecC;
  /***** -mask: File containing masking information to use */
  int maskfileP;
  char *maskfile;
  int maskfileC;
  /***** -ignorechan: Comma separated string (no spaces!) of channels to ignore (or file containing such string).  Ranges are specified by min:max[:step] */
  int ignorechanstrP;
  char *ignorechanstr;
  int ignorechanstrC;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* PREPSUBBAND_CMD_H */
