#ifndef PREPFOLD_MULTI_CMD_H
#define PREPFOLD_MULTI_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

/*
  SHARED-STRUCT LAYOUT INVARIANT (do not break):

  prepfold_multi reuses prepfold_pipeline.c, which reads this `Cmdline` through
  prepfold's field names.  This struct is therefore prepfold_cmd.h's s_Cmdline
  with ONE field (`candfile`) appended AFTER `full_cmd_line` -- so every field the
  shared pipeline touches keeps prepfold's offset.  Add new prepfold_multi-only
  fields ONLY at the end; never reorder, retype, or remove the shared prefix.

  Human-facing option surface: clig/prepfold_multi_cmd.cli.
  The prefix invariant is enforced by tests/prepfold/check_cmd_layout.sh (wired
  into tests/prepfold/prepfold_tests.sh): it asserts prepfold_cmd.h's s_Cmdline
  body is a line-for-line prefix of this header's, and fails on any drift.
*/

typedef struct s_Cmdline {
  /***** -ncpus: Number of processors to use with OpenMP */
  int ncpusP;
  int ncpus;
  int ncpusC;
  /***** -o: Root of the output file names */
  int outfileP;
  char *outfile;
  int outfileC;
  /***** -filterbank: Raw data in SIGPROC filterbank format */
  int filterbankP;
  /***** -psrfits: Raw data in PSRFITS format */
  int psrfitsP;
  /***** -noweights: Do not apply PSRFITS weights */
  int noweightsP;
  /***** -noscales: Do not apply PSRFITS scales */
  int noscalesP;
  /***** -nooffsets: Do not apply PSRFITS offsets */
  int nooffsetsP;
  /***** -wapp: Raw data in Wideband Arecibo Pulsar Processor (WAPP) format */
  int wappP;
  /***** -window: Window correlator lags with a Hamming window before FFTing */
  int windowP;
  /***** -topo: Fold the data topocentrically (i.e. don't barycenter) */
  int topoP;
  /***** -invert: For rawdata, flip (or invert) the band */
  int invertP;
  /***** -zerodm: Subtract the mean of all channels from each sample (i.e. remove zero DM) */
  int zerodmP;
  /***** -absphase: Use the absolute phase associated with polycos */
  int absphaseP;
  /***** -barypolycos: Force the use of polycos for barycentered events */
  int barypolycosP;
  /***** -debug: Show debugging output when calling TEMPO for polycos */
  int debugP;
  /***** -samples: Treat the data as samples and not as finite-duration integrated data */
  int samplesP;
  /***** -normalize: Bandpass flatten the data by normalizing the subbands */
  int normalizeP;
  /***** -numwapps: Number of WAPPs used with contiguous frequencies */
  int numwappsP;
  int numwapps;
  int numwappsC;
  /***** -if: A specific IF to use if available (summed IFs is the default) */
  int ifsP;
  int ifs;
  int ifsC;
  /***** -clip: Time-domain sigma to use for clipping (0.0 = no clipping, 6.0 = default */
  int clipP;
  float clip;
  int clipC;
  /***** -noclip: Do not clip the data.  (The default is to _always_ clip!) */
  int noclipP;
  /***** -noxwin: Do not show the result plots on-screen, only make postscript files */
  int noxwinP;
  /***** -runavg: Subtract each blocks average as it is read (single channel data only) */
  int runavgP;
  /***** -fine: A finer gridding in the p/pdot plane (for well known p and pdot) */
  int fineP;
  /***** -coarse: A coarser gridding in the p/pdot plane (for uknown p and pdot) */
  int coarseP;
  /***** -slow: Sets useful flags for slow pulsars */
  int slowP;
  /***** -searchpdd: Search p-dotdots as well as p and p-dots */
  int searchpddP;
  /***** -searchfdd: Search f-dotdots as well as f and f-dots */
  int searchfddP;
  /***** -nosearch: Show but do not search the p/pdot and/or DM phase spaces */
  int nosearchP;
  /***** -nopsearch: Show but do not search over period */
  int nopsearchP;
  /***** -nopdsearch: Show but do not search over p-dot */
  int nopdsearchP;
  /***** -nodmsearch: Show but do not search over DM */
  int nodmsearchP;
  /***** -scaleparts: Scale the part profiles independently */
  int scalepartsP;
  /***** -allgrey: Make all the images greyscale instead of color */
  int allgreyP;
  /***** -fixchi: Adjust the reduced chi^2 values so that off-pulse reduced chi^2 = 1 */
  int fixchiP;
  /***** -justprofs: Only output the profile portions of the plot */
  int justprofsP;
  /***** -dm: The central DM of the search (cm^-3 pc) */
  int dmP;
  double dm;
  int dmC;
  /***** -n: The number of bins in the profile.  Defaults to the number of sampling bins which correspond to one folded period */
  int proflenP;
  int proflen;
  int proflenC;
  /***** -nsub: The number of sub-bands to use for the DM search.  If unspecified, will use something reasonable. */
  int nsubP;
  int nsub;
  int nsubC;
  /***** -npart: The number of sub-integrations to use for the period search */
  int npartP;
  int npart;
  int npartC;
  /***** -pstep: The minimum period stepsize over the observation in profile bins */
  int pstepP;
  int pstep;
  int pstepC;
  /***** -pdstep: The minimum P-dot stepsize over the observation in profile bins */
  int pdstepP;
  int pdstep;
  int pdstepC;
  /***** -dmstep: The minimum DM stepsize over the observation in profile bins */
  int dmstepP;
  int dmstep;
  int dmstepC;
  /***** -npfact: 2 * npfact * proflen + 1 periods and p-dots will be searched */
  int npfactP;
  int npfact;
  int npfactC;
  /***** -ndmfact: 2 * ndmfact * proflen + 1 DMs will be searched */
  int ndmfactP;
  int ndmfact;
  int ndmfactC;
  /***** -p: The nominative folding period (s) */
  int pP;
  double p;
  int pC;
  /***** -pd: The nominative period derivative (s/s) */
  int pdP;
  double pd;
  int pdC;
  /***** -pdd: The nominative period 2nd derivative (s/s^2) */
  int pddP;
  double pdd;
  int pddC;
  /***** -f: The nominative folding frequency (hz) */
  int fP;
  double f;
  int fC;
  /***** -fd: The nominative frequency derivative (hz/s) */
  int fdP;
  double fd;
  int fdC;
  /***** -fdd: The nominative frequency 2nd derivative (hz/s^2) */
  int fddP;
  double fdd;
  int fddC;
  /***** -pfact: A factor to multiple the candidate p and p-dot by */
  int pfactP;
  double pfact;
  int pfactC;
  /***** -ffact: A factor to multiple the candidate f and f-dot by */
  int ffactP;
  double ffact;
  int ffactC;
  /***** -phs: Offset phase for the profil */
  int phsP;
  double phs;
  int phsC;
  /***** -start: The folding start time as a fraction of the full obs */
  int startTP;
  double startT;
  int startTC;
  /***** -end: The folding end time as a fraction of the full obs */
  int endTP;
  double endT;
  int endTC;
  /***** -psr: Name of pulsar to fold (do not include J or B) */
  int psrnameP;
  char *psrname;
  int psrnameC;
  /***** -par: Name of a TEMPO par file from which to get PSR params */
  int parnameP;
  char *parname;
  int parnameC;
  /***** -polycos: File containing TEMPO polycos for psrname (not required) */
  int polycofileP;
  char *polycofile;
  int polycofileC;
  /***** -timing: Sets useful flags for TOA generation. Generates polycos (if required) based on the par file specified as the argument. (This means you don't need the -par or -psr commands!) */
  int timingP;
  char *timing;
  int timingC;
  /***** -rzwcand: The candidate number to fold from 'infile'_rzw.cand */
  int rzwcandP;
  int rzwcand;
  int rzwcandC;
  /***** -rzwfile: Name of the rzw search '.cand' file to use (with suffix) */
  int rzwfileP;
  char *rzwfile;
  int rzwfileC;
  /***** -accelcand: The candidate number to fold from 'infile'_rzw.cand */
  int accelcandP;
  int accelcand;
  int accelcandC;
  /***** -accelfile: Name of the accel search '.cand' file to use (with suffix) */
  int accelfileP;
  char *accelfile;
  int accelfileC;
  /***** -bin: Fold a binary pulsar.  Must include all of the following parameters */
  int binaryP;
  /***** -pb: The orbital period (s) */
  int pbP;
  double pb;
  int pbC;
  /***** -x: The projected orbital semi-major axis (lt-sec) */
  int asinicP;
  double asinic;
  int asinicC;
  /***** -e: The orbital eccentricity */
  int eP;
  double e;
  int eC;
  /***** -To: The time of periastron passage (MJD) */
  int ToP;
  double To;
  int ToC;
  /***** -w: Longitude of periastron (deg) */
  int wP;
  double w;
  int wC;
  /***** -wdot: Rate of advance of periastron (deg/yr) */
  int wdotP;
  double wdot;
  int wdotC;
  /***** -mask: File containing masking information to use */
  int maskfileP;
  char *maskfile;
  int maskfileC;
  /***** -ignorechan: Comma separated string (no spaces!) of channels to ignore (or file containing such string).  Ranges are specified by min:max[:step] */
  int ignorechanstrP;
  char *ignorechanstr;
  int ignorechanstrC;
  /***** -events: Use a event file instead of a time series (.dat) file */
  int eventsP;
  /***** -days: Events are in days since the EPOCH in the '.inf' file (default is seconds) */
  int daysP;
  /***** -mjds: Events are in MJDs */
  int mjdsP;
  /***** -double: Events are in binary double precision (default is ASCII) */
  int doubleP;
  /***** -offset: A time offset to add to the 1st event in the same units as the events */
  int offsetP;
  double offset;
  int offsetC;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
  /***** -candfile: Text file listing candidates to fold (one per row; '#' header names the columns -- see prepfold_multi(1)) */
  int candfileP;
  char *candfile;
  int candfileC;
} Cmdline;


extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* PREPFOLD_MULTI_CMD_H */
