#ifndef READFILE_CMD_H
#define READFILE_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -page: Paginate the output like 'more' */
  int pageP;
  /***** -byte: Raw data in byte format */
  int bytP;
  /***** -b: Raw data in byte format */
  int sbytP;
  /***** -float: Raw data in floating point format */
  int fltP;
  /***** -f: Raw data in floating point format */
  int sfltP;
  /***** -double: Raw data in double precision format */
  int dblP;
  /***** -d: Raw data in double precision format */
  int sdblP;
  /***** -fcomplex: Raw data in float-complex format */
  int fcxP;
  /***** -fc: Raw data in float-complex format */
  int sfcxP;
  /***** -dcomplex: Raw data in double-complex format */
  int dcxP;
  /***** -dc: Raw data in double-complex format */
  int sdcxP;
  /***** -short: Raw data in short format */
  int shtP;
  /***** -s: Raw data in short format */
  int sshtP;
  /***** -int: Raw data in integer format */
  int igrP;
  /***** -i: Raw data in integer format */
  int sigrP;
  /***** -long: Raw data in long format */
  int lngP;
  /***** -l: Raw data in long format */
  int slngP;
  /***** -rzwcand: Raw data in rzw search candidate format */
  int rzwP;
  /***** -rzw: Raw data in rzw search candidate format */
  int srzwP;
  /***** -bincand: Raw data in bin search candidate format */
  int binP;
  /***** -bin: Raw data in bin search candidate format */
  int sbinP;
  /***** -position: Raw data in position struct format */
  int posP;
  /***** -pos: Raw data in position struct format */
  int sposP;
  /***** -pkmb: Raw data in Parkes Multibeam format */
  int pkmbP;
  /***** -bcpm: Raw data in BCPM format */
  int bcpmP;
  /***** -wapp: Raw data in WAPP format */
  int wappP;
  /***** -spigot: Raw data in Spigot Card format */
  int spigotP;
  /***** -filterbank: Raw data in SIGPROC filterbank format */
  int filterbankP;
  /***** -psrfits: Raw data in PSRFITS format */
  int psrfitsP;
  /***** -fortran: Raw data was written by a fortran program */
  int fortranP;
  /***** -index: The range of objects to display */
  int indexP;
  int *index;
  int indexC;
  /***** -nph: 0th FFT bin amplitude (for 'RZW' data) */
  int nphP;
  double nph;
  int nphC;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* READFILE_CMD_H */
