#ifndef REALFFT_CMD_H
#define REALFFT_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -fwd: Force an forward FFT (sign=-1) to be performed */
  int forwardP;
  /***** -inv: Force an inverse FFT (sign=+1) to be performed */
  int inverseP;
  /***** -del: Delete the original file(s) when performing the FFT */
  int deleteP;
  /***** -disk: Force the use of the out-of-core memory FFT */
  int diskfftP;
  /***** -mem: Force the use of the in-core memory FFT */
  int memfftP;
  /***** -tmpdir: Scratch directory for temp file(s) in out-of-core FFT */
  int tmpdirP;
  char *tmpdir;
  int tmpdirC;
  /***** -outdir: Directory where result file(s) will reside */
  int outdirP;
  char *outdir;
  int outdirC;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* REALFFT_CMD_H */
