#ifndef RFIFIND_CMD_H
#define RFIFIND_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -ncpus: Number of processors to use with OpenMP */
  int ncpusP;
  int ncpus;
  int ncpusC;
  /***** -o: Root of the output file names */
  int outfileP;
  char *outfile;
  int outfileC;
  /***** -filterbank: Raw data in SIGPROC filterbank format */
  int filterbankP;
  /***** -psrfits: Raw data in PSRFITS format */
  int psrfitsP;
  /***** -noweights: Do not apply PSRFITS weights */
  int noweightsP;
  /***** -noscales: Do not apply PSRFITS scales */
  int noscalesP;
  /***** -nooffsets: Do not apply PSRFITS offsets */
  int nooffsetsP;
  /***** -wapp: Raw data in Wideband Arecibo Pulsar Processor (WAPP) format */
  int wappP;
  /***** -window: Window correlator lags with a Hamming window before FFTing */
  int windowP;
  /***** -numwapps: Number of WAPPs used with contiguous frequencies */
  int numwappsP;
  int numwapps;
  int numwappsC;
  /***** -if: A specific IF to use if available (summed IFs is the default) */
  int ifsP;
  int ifs;
  int ifsC;
  /***** -clip: Time-domain sigma to use for clipping (0.0 = no clipping, 6.0 = default */
  int clipP;
  float clip;
  int clipC;
  /***** -noclip: Do not clip the data.  (The default is to _always_ clip!) */
  int noclipP;
  /***** -invert: For rawdata, flip (or invert) the band */
  int invertP;
  /***** -zerodm: Subtract the mean of all channels from each sample (i.e. remove zero DM) */
  int zerodmP;
  /***** -xwin: Draw plots to the screen as well as a PS file */
  int xwinP;
  /***** -nocompute: Just plot and remake the mask */
  int nocomputeP;
  /***** -rfixwin: Show the RFI instances on screen */
  int rfixwinP;
  /***** -rfips: Plot the RFI instances in a PS file */
  int rfipsP;
  /***** -time: Seconds to integrate for stats and FFT calcs (use this or -blocks) */
  int timeP;
  double time;
  int timeC;
  /***** -blocks: Number of blocks (usually 16-1024 samples) to integrate for stats and FFT calcs */
  int blocksP;
  int blocks;
  int blocksC;
  /***** -timesig: The +/-sigma cutoff to reject time-domain chunks */
  int timesigmaP;
  float timesigma;
  int timesigmaC;
  /***** -freqsig: The +/-sigma cutoff to reject freq-domain chunks */
  int freqsigmaP;
  float freqsigma;
  int freqsigmaC;
  /***** -chanfrac: The fraction of bad channels that will mask a full interval */
  int chantrigfracP;
  float chantrigfrac;
  int chantrigfracC;
  /***** -intfrac: The fraction of bad intervals that will mask a full channel */
  int inttrigfracP;
  float inttrigfrac;
  int inttrigfracC;
  /***** -zapchan: Comma separated string (no spaces!) of channels to explicitly mask.  Ranges are specified by min:max[:step] */
  int zapchanstrP;
  char *zapchanstr;
  int zapchanstrC;
  /***** -zapints: Comma separated string (no spaces!) of intervals to explicitly mask.  Ranges are specified by min:max[:step] */
  int zapintsstrP;
  char *zapintsstr;
  int zapintsstrC;
  /***** -mask: File containing masking information to use */
  int maskfileP;
  char *maskfile;
  int maskfileC;
  /***** -ignorechan: Comma separated string (no spaces!) of channels to ignore (or file containing such string).  Ranges are specified by min:max[:step] */
  int ignorechanstrP;
  char *ignorechanstr;
  int ignorechanstrC;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* RFIFIND_CMD_H */
