#ifndef SEARCH_BIN_CMD_H
#define SEARCH_BIN_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -ncand: Number of candidates to try to return */
  int ncandP;
  int ncand;
  int ncandC;
  /***** -minfft: Power-of-2 length of the shortest miniFFT */
  int minfftP;
  int minfft;
  int minfftC;
  /***** -maxfft: Power-of-2 length of the longest miniFFT */
  int maxfftP;
  int maxfft;
  int maxfftC;
  /***** -flo: The low frequency (Hz) to check */
  int floP;
  float flo;
  int floC;
  /***** -fhi: The high frequency (Hz) to check */
  int fhiP;
  float fhi;
  int fhiC;
  /***** -rlo: The low Fourier frequency to check */
  int rloP;
  int rlo;
  int rloC;
  /***** -rhi: The high Fourier frequency to check */
  int rhiP;
  int rhi;
  int rhiC;
  /***** -lobin: The first Fourier frequency in the data file */
  int lobinP;
  int lobin;
  int lobinC;
  /***** -overlap: Fraction of a short FFT length to shift before performing another */
  int overlapP;
  double overlap;
  int overlapC;
  /***** -harmsum: Number of harmonics to sum in the miniFFTs */
  int harmsumP;
  int harmsum;
  int harmsumC;
  /***** -numbetween: Number of points to interpolate per Fourier bin (2 gives the usual bin value and an interbin) */
  int numbetweenP;
  int numbetween;
  int numbetweenC;
  /***** -stack: Number of stacked power spectra making up the data.  (The default means the data are complex amplitudes) */
  int stackP;
  int stack;
  int stackC;
  /***** -interbin: Use interbinning instead of full-blown Fourier interpolation.  (Faster but less accurate and sensitive) */
  int interbinP;
  /***** -noalias: Do not add aliased powers to the harmonic sum.  (Faster but less accurate and sensitive) */
  int noaliasP;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* SEARCH_BIN_CMD_H */
