#ifndef SHOW_PFD_CMD_H
#define SHOW_PFD_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -noxwin: Do not show the result plots on-screen, only make postscript files */
  int noxwinP;
  /***** -showfold: Use the input fold paramters (i.e. not the optimized values) when showing the plot */
  int showfoldP;
  /***** -scaleparts: Scale the part profiles independently */
  int scalepartsP;
  /***** -allgrey: Make all the images greyscale instead of color */
  int allgreyP;
  /***** -justprofs: Only output the profile portions of the plot */
  int justprofsP;
  /***** -portrait: Orient the output in portrait mode (for -justprofs) */
  int portraitP;
  /***** -events: The folded data were events instead of samples or bins */
  int eventsP;
  /***** -infoonly: Display the pfd info and exit without generating plots. */
  int infoonlyP;
  /***** -fixchi: Adjust the reduced chi^2 values so that off-pulse reduced chi^2 = 1 */
  int fixchiP;
  /***** -samples: Treat the data as samples and not as finite-duration integrated data */
  int samplesP;
  /***** -normalize: Normalize stats for each fold (i.e. to bandpass flatten subbands) */
  int normalizeP;
  /***** -killsubs: Comma separated string (no spaces!) of subbands to explicitly remove from analysis (i.e. zero out).  Ranges are specified by min:max[:step] */
  int killsubsstrP;
  char *killsubsstr;
  int killsubsstrC;
  /***** -killparts: Comma separated string (no spaces!) of intervals to explicitly remove from analysis (i.e. zero-out).  Ranges are specified by min:max[:step] */
  int killpartsstrP;
  char *killpartsstr;
  int killpartsstrC;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* SHOW_PFD_CMD_H */
