#ifndef TOAS2DAT_CMD_H
#define TOAS2DAT_CMD_H
/****
  command line parser interface -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

typedef struct s_Cmdline {
  /***** -n: The number of bins in the output time series */
  int numoutP;
  long numout;
  int numoutC;
  /***** -dt: Time interval in seconds for output time bins */
  int dtP;
  double dt;
  int dtC;
  /***** -t0: Time for the start of bin 0 (same units as the TOAs) */
  int t0P;
  double t0;
  int t0C;
  /***** -o: Name of the output time series file */
  int outfileP;
  char *outfile;
  int outfileC;
  /***** -text: TOAs are ASCII text (default is binary double) */
  int textP;
  /***** -float: TOAs are binary floats (default is binary double) */
  int floatP;
  /***** -sec: TOA unit is seconds (default is days) */
  int secP;
  /***** uninterpreted command line parameters */
  int argc;
  char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

extern char *Program;
extern void usage(void);
extern Cmdline *parseCmdline(int argc, char **argv);
extern void showOptionValues(void);

#endif  /* TOAS2DAT_CMD_H */
