#include <presto.h>

/* Compare polycos generated by tempo2 (the new make_polycos()) against */
/* those from TEMPO (make_polycos_tempo1()) by evaluating the predicted */
/* phase and spin frequency on a dense time grid with the standard      */
/* getpoly()/phcalc() machinery.  Requires both 'tempo' and 'tempo2';   */
/* skipped (exit 77) otherwise.                                         */
/*                                                                      */
/* What to expect:  a *constant* phase offset between the two (clock-   */
/* chain and phase-reference conventions differ at the ~us level, just  */
/* as with the ERFA barycentering swap), but tiny *differential* phase  */
/* drift (what folding actually feels) and tiny frequency differences.  */
/*                                                                      */
/* Usage:  check_polycos_t2 [path-to-tests/prepfold]                    */

extern int getpoly(double mjd, double duration, double *dm, FILE * fp,
                   char *pname);
extern int phcalc(double mjd0, double mjd1, int last_index, double *phase,
                  double *psrfreq);
extern char *make_polycos(char *parfilenm, infodata * idata,
                          char *polycofilenm, int debug);
extern char *make_polycos_tempo1(char *parfilenm, infodata * idata,
                                 char *polycofilenm, int debug);

#define NUMPTS 3456             /* 0.4 days every 10 s */

static char *testpars[] = { "Ter5A.par", "Ter5N.par", "M28A.par", "M28A.par" };
static char *testscopes[] = { "GBT", "Parkes", "GBT", "Unknown" };

static void eval_polycos(char *filenm, char *psrname, infodata * idata,
                         double T, double *phases, double *freqs)
/* Fill phases/freqs evaluated every 10 s across the observation */
{
    FILE *fp;
    double dm, mjdf;
    int ii, nsets, idx = 0;

    fp = chkfopen(filenm, "r");
    nsets = getpoly(idata->mjd_i + idata->mjd_f, T, &dm, fp, psrname);
    fclose(fp);
    if (nsets == 0) {
        fprintf(stderr, "\nError:  no polycos read from '%s'!\n", filenm);
        exit(1);
    }
    for (ii = 0; ii < NUMPTS; ii++) {
        mjdf = idata->mjd_f + ii * 10.0 / SECPERDAY;
        idx = phcalc(idata->mjd_i, mjdf, idx, &phases[ii], &freqs[ii]);
    }
}

int main(int argc, char *argv[])
{
    char *pardir = "tests/prepfold";
    char parfilenm[256], *psrname1, *psrname2;
    double ph1[NUMPTS], f1[NUMPTS], ph2[NUMPTS], f2[NUMPTS];
    double maxdiffdev = 0.0, maxfreqdiff = 0.0;
    infodata idata;
    int cc, ii, retval = 0, numcases = 4;

    if (system("which tempo > /dev/null 2>&1") != 0 ||
        system("which tempo2 > /dev/null 2>&1") != 0) {
        printf("TEMPO and/or tempo2 unavailable:  skipping the polyco "
               "comparison.\n");
        return 77;
    }
    if (argc > 1)
        pardir = argv[1];

    printf("Comparing tempo2 and TEMPO polycos (%d cases, %d points each):\n\n",
           numcases, NUMPTS);
    for (cc = 0; cc < numcases; cc++) {
        double offset, dev, casedev = 0.0, casefreq = 0.0;

        /* A fake 0.4-day observation at 1400 MHz */
        memset(&idata, 0, sizeof(infodata));
        strcpy(idata.telescope, testscopes[cc]);
        idata.mjd_i = 54721;
        idata.mjd_f = 0.35;
        idata.dt = 64e-6;
        idata.N = 0.4 * SECPERDAY / idata.dt;
        idata.freq = 1400.0;
        idata.num_chan = 1024;
        idata.chan_wid = 0.1953125;

        sprintf(parfilenm, "%s/%s", pardir, testpars[cc]);
        psrname1 = make_polycos_tempo1(parfilenm, &idata, "pc_t1.tmp", 0);
        psrname2 = make_polycos(parfilenm, &idata, "pc_t2.tmp", 0);
        eval_polycos("pc_t1.tmp", psrname1, &idata, 0.4, ph1, f1);
        eval_polycos("pc_t2.tmp", psrname2, &idata, 0.4, ph2, f2);

        /* Constant phase offset (conventions), from the first point */
        offset = ph2[0] - ph1[0];
        offset -= round(offset);
        for (ii = 0; ii < NUMPTS; ii++) {
            dev = (ph2[ii] - ph1[ii]) - offset;
            dev -= round(dev);
            if (fabs(dev) > casedev)
                casedev = fabs(dev);
            if (fabs(f2[ii] - f1[ii]) / f1[ii] > casefreq)
                casefreq = fabs(f2[ii] - f1[ii]) / f1[ii];
        }
        printf("  %-10s @ %-10s:  const offset = %10.3e turns (%8.3f us),\n"
               "      differential drift = %10.3e turns,  max |df|/f = %10.3e\n",
               psrname1, testscopes[cc], offset, offset / f1[0] * 1e6,
               casedev, casefreq);
        if (casedev > maxdiffdev)
            maxdiffdev = casedev;
        if (casefreq > maxfreqdiff)
            maxfreqdiff = casefreq;
        free(psrname1);
        free(psrname2);
        remove("pc_t1.tmp");
        remove("pc_t2.tmp");
    }

    printf("\nOverall:  max differential drift = %.3e turns,  "
           "max |df|/f = %.3e\n", maxdiffdev, maxfreqdiff);
    /* Thresholds:  see ROADMAP.md for the measured values behind these */
    if (maxdiffdev > 1e-4) {
        printf("FAILURE:  differential phase drift exceeds 1e-4 turns!\n");
        retval = 1;
    }
    if (maxfreqdiff > 1e-9) {
        printf("FAILURE:  frequency differences exceed 1e-9 relative!\n");
        retval = 1;
    }
    if (retval == 0)
        printf("\nAll comparisons passed.\n");
    return retval;
}
