/****
  command line parser -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include <math.h>

#include "downsample_cmd.h"

char *Program;

static Cmdline cmd = {
    /***** -factor: The factor to downsample the data */
    /* factorP = */ 0,
    /* factor = */ 0,
    /* factorC = */ 0,
    /***** -o: Name of the output time series file (with suffix) */
    /* outfileP = */ 0,
    /* outfile = */ NULL,
    /* outfileC = */ 0,
    /***** uninterpreted rest of command line */
    /* argc = */ 0,
    /* argv = */ NULL,
    /***** the original command line concatenated */
    /* full_cmd_line = */ NULL
};

/*********************************************************************/

int getIntOpt(int argc, char **argv, int i, int *value, int force)
{
    char *end;
    long v;

    if (++i >= argc)
        goto nothingFound;

    errno = 0;
    v = strtol(argv[i], &end, 0);

    if (end == argv[i])
        goto nothingFound;

    while (isspace((unsigned char) *end))
        end++;
    if (*end)
        goto nothingFound;

    if (errno == ERANGE || v > (long) INT_MAX || v < (long) INT_MIN) {
        fprintf(stderr,
                "%s: parameter `%s' of option `%s' too large to represent\n",
                Program, argv[i], argv[i - 1]);
        exit(EXIT_FAILURE);
    }
    *value = (int) v;
    return i;

  nothingFound:
    if (!force)
        return i - 1;
    fprintf(stderr,
            "%s: missing or malformed integer value after option `%s'\n",
            Program, argv[i - 1]);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

int getStringOpt(int argc, char **argv, int i, char **value, int force)
{
    i += 1;
    if (i >= argc) {
        if (force) {
            fprintf(stderr, "%s: missing string after option `%s'\n",
                    Program, argv[i - 1]);
            exit(EXIT_FAILURE);
        }
        return i - 1;
    }

    if (!force && argv[i][0] == '-')
        return i - 1;
    *value = argv[i];
    return i;
}

/*********************************************************************/

void checkIntLower(const char *opt, int *values, int count, int max)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] <= max)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' greater than max=%d\n",
                Program, i + 1, opt, max);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

void checkIntHigher(const char *opt, int *values, int count, int min)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] >= min)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' smaller than min=%d\n",
                Program, i + 1, opt, min);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

static void missingErr(const char *opt)
{
    fprintf(stderr, "%s: mandatory option `%s' missing\n", Program, opt);
}

/*********************************************************************/

static char *catArgv(int argc, char **argv)
{
    int i;
    size_t l, pos, n;
    char *s;

    for (i = 0, l = 1; i < argc; i++)
        l += strlen(argv[i]) + 1;
    s = (char *) malloc(l);
    if (!s) {
        fprintf(stderr, "%s: out of memory\n", Program);
        exit(EXIT_FAILURE);
    }
    for (i = 0, pos = 0; i < argc; i++) {
        n = strlen(argv[i]);
        if (i > 0)
            s[pos++] = ' ';
        memcpy(s + pos, argv[i], n);
        pos += n;
    }
    s[pos] = '\0';
    return s;
}

/*********************************************************************/

void showOptionValues(void)
{
    int i;

    printf("Full command line is:\n`%s'\n", cmd.full_cmd_line);

    /***** -factor: The factor to downsample the data */
    if (!cmd.factorP) {
        printf("-factor not found.\n");
    } else {
        printf("-factor found:\n");
        if (!cmd.factorC) {
            printf("  no values\n");
        } else {
            printf("  value = `%d'\n", cmd.factor);
        }
    }

    /***** -o: Name of the output time series file (with suffix) */
    if (!cmd.outfileP) {
        printf("-o not found.\n");
    } else {
        printf("-o found:\n");
        if (!cmd.outfileC) {
            printf("  no values\n");
        } else {
            printf("  value = `%s'\n", cmd.outfile);
        }
    }

    if (!cmd.argc) {
        printf("no remaining parameters in argv\n");
    } else {
        printf("argv =");
        for (i = 0; i < cmd.argc; i++)
            printf(" `%s'", cmd.argv[i]);
        printf("\n");
    }
}

/*********************************************************************/

void usage(void)
{
    fputs("   -factor factor [-o outfile] [--] file\n", stderr);
    fputs("      Downsamples a time series.\n", stderr);
    fputs("    -factor: The factor to downsample the data\n", stderr);
    fputs("             1 int value between 1 and 100\n", stderr);
    fputs("         -o: Name of the output time series file (with suffix)\n", stderr);
    fputs("             1 char* value\n", stderr);
    fputs("       file: Input '.dat' or '.sdat' file name\n", stderr);
    fputs("             1 value\n", stderr);
    fputs("  CLI code generated: 03Jul26\n", stderr);
    fputs("  ", stderr);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

Cmdline *parseCmdline(int argc, char **argv)
{
    int i;
    int missingMandatory = 0;

    Program = argv[0];
    cmd.full_cmd_line = catArgv(argc, argv);
    for (i = 1, cmd.argc = 1; i < argc; i++) {

        if (0 == strcmp("--", argv[i])) {
            while (++i < argc)
                argv[cmd.argc++] = argv[i];
            continue;
        }

        if (0 == strcmp("-factor", argv[i])) {
            int keep = i;
            cmd.factorP = 1;
            i = getIntOpt(argc, argv, i, &cmd.factor, 1);
            cmd.factorC = i - keep;
            checkIntLower("-factor", &cmd.factor, cmd.factorC, 100);
            checkIntHigher("-factor", &cmd.factor, cmd.factorC, 1);
            continue;
        }

        if (0 == strcmp("-o", argv[i])) {
            int keep = i;
            cmd.outfileP = 1;
            i = getStringOpt(argc, argv, i, &cmd.outfile, 1);
            cmd.outfileC = i - keep;
            continue;
        }

        if (argv[i][0] == '-') {
            fprintf(stderr, "\n%s: unknown option `%s'\n\n",
                    Program, argv[i]);
            usage();
        }
        argv[cmd.argc++] = argv[i];
    }

    if (!cmd.factorP) {
        missingErr("-factor");
        missingMandatory = 1;
    }
    if (missingMandatory)
        exit(EXIT_FAILURE);

    cmd.argv = argv + 1;
    cmd.argc -= 1;

    if (1 > cmd.argc) {
        fprintf(stderr,
                "%s: there should be at least 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    if (1 < cmd.argc) {
        fprintf(stderr,
                "%s: there should be at most 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    return &cmd;
}
