/****
  command line parser -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include <math.h>

#include "realfft_cmd.h"

char *Program;

static Cmdline cmd = {
    /***** -fwd: Force an forward FFT (sign=-1) to be performed */
    /* forwardP = */ 0,
    /***** -inv: Force an inverse FFT (sign=+1) to be performed */
    /* inverseP = */ 0,
    /***** -del: Delete the original file(s) when performing the FFT */
    /* deleteP = */ 0,
    /***** -disk: Force the use of the out-of-core memory FFT */
    /* diskfftP = */ 0,
    /***** -mem: Force the use of the in-core memory FFT */
    /* memfftP = */ 0,
    /***** -tmpdir: Scratch directory for temp file(s) in out-of-core FFT */
    /* tmpdirP = */ 0,
    /* tmpdir = */ NULL,
    /* tmpdirC = */ 0,
    /***** -outdir: Directory where result file(s) will reside */
    /* outdirP = */ 0,
    /* outdir = */ NULL,
    /* outdirC = */ 0,
    /***** uninterpreted rest of command line */
    /* argc = */ 0,
    /* argv = */ NULL,
    /***** the original command line concatenated */
    /* full_cmd_line = */ NULL
};

/*********************************************************************/

int getStringOpt(int argc, char **argv, int i, char **value, int force)
{
    i += 1;
    if (i >= argc) {
        if (force) {
            fprintf(stderr, "%s: missing string after option `%s'\n",
                    Program, argv[i - 1]);
            exit(EXIT_FAILURE);
        }
        return i - 1;
    }

    if (!force && argv[i][0] == '-')
        return i - 1;
    *value = argv[i];
    return i;
}

/*********************************************************************/

static char *catArgv(int argc, char **argv)
{
    int i;
    size_t l, pos, n;
    char *s;

    for (i = 0, l = 1; i < argc; i++)
        l += strlen(argv[i]) + 1;
    s = (char *) malloc(l);
    if (!s) {
        fprintf(stderr, "%s: out of memory\n", Program);
        exit(EXIT_FAILURE);
    }
    for (i = 0, pos = 0; i < argc; i++) {
        n = strlen(argv[i]);
        if (i > 0)
            s[pos++] = ' ';
        memcpy(s + pos, argv[i], n);
        pos += n;
    }
    s[pos] = '\0';
    return s;
}

/*********************************************************************/

void showOptionValues(void)
{
    int i;

    printf("Full command line is:\n`%s'\n", cmd.full_cmd_line);

    /***** -fwd: Force an forward FFT (sign=-1) to be performed */
    if (!cmd.forwardP) {
        printf("-fwd not found.\n");
    } else {
        printf("-fwd found:\n");
    }

    /***** -inv: Force an inverse FFT (sign=+1) to be performed */
    if (!cmd.inverseP) {
        printf("-inv not found.\n");
    } else {
        printf("-inv found:\n");
    }

    /***** -del: Delete the original file(s) when performing the FFT */
    if (!cmd.deleteP) {
        printf("-del not found.\n");
    } else {
        printf("-del found:\n");
    }

    /***** -disk: Force the use of the out-of-core memory FFT */
    if (!cmd.diskfftP) {
        printf("-disk not found.\n");
    } else {
        printf("-disk found:\n");
    }

    /***** -mem: Force the use of the in-core memory FFT */
    if (!cmd.memfftP) {
        printf("-mem not found.\n");
    } else {
        printf("-mem found:\n");
    }

    /***** -tmpdir: Scratch directory for temp file(s) in out-of-core FFT */
    if (!cmd.tmpdirP) {
        printf("-tmpdir not found.\n");
    } else {
        printf("-tmpdir found:\n");
        if (!cmd.tmpdirC) {
            printf("  no values\n");
        } else {
            printf("  value = `%s'\n", cmd.tmpdir);
        }
    }

    /***** -outdir: Directory where result file(s) will reside */
    if (!cmd.outdirP) {
        printf("-outdir not found.\n");
    } else {
        printf("-outdir found:\n");
        if (!cmd.outdirC) {
            printf("  no values\n");
        } else {
            printf("  value = `%s'\n", cmd.outdir);
        }
    }

    if (!cmd.argc) {
        printf("no remaining parameters in argv\n");
    } else {
        printf("argv =");
        for (i = 0; i < cmd.argc; i++)
            printf(" `%s'", cmd.argv[i]);
        printf("\n");
    }
}

/*********************************************************************/

void usage(void)
{
    fputs("   [-fwd] [-inv] [-del] [-disk] [-mem] [-tmpdir tmpdir] [-outdir outdir] [--] infiles ...\n", stderr);
    fputs("      Perform a single-precision FFT of real data or its inverse\n", stderr);
    fputs("       -fwd: Force an forward FFT (sign=-1) to be performed\n", stderr);
    fputs("       -inv: Force an inverse FFT (sign=+1) to be performed\n", stderr);
    fputs("       -del: Delete the original file(s) when performing the FFT\n", stderr);
    fputs("      -disk: Force the use of the out-of-core memory FFT\n", stderr);
    fputs("       -mem: Force the use of the in-core memory FFT\n", stderr);
    fputs("    -tmpdir: Scratch directory for temp file(s) in out-of-core FFT\n", stderr);
    fputs("             1 char* value\n", stderr);
    fputs("    -outdir: Directory where result file(s) will reside\n", stderr);
    fputs("             1 char* value\n", stderr);
    fputs("    infiles: Input data file(s)\n", stderr);
    fputs("             1...16384 values\n", stderr);
    fputs("  CLI code generated: 03Jul26\n", stderr);
    fputs("  ", stderr);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

Cmdline *parseCmdline(int argc, char **argv)
{
    int i;

    Program = argv[0];
    cmd.full_cmd_line = catArgv(argc, argv);
    for (i = 1, cmd.argc = 1; i < argc; i++) {

        if (0 == strcmp("--", argv[i])) {
            while (++i < argc)
                argv[cmd.argc++] = argv[i];
            continue;
        }

        if (0 == strcmp("-fwd", argv[i])) {
            cmd.forwardP = 1;
            continue;
        }

        if (0 == strcmp("-inv", argv[i])) {
            cmd.inverseP = 1;
            continue;
        }

        if (0 == strcmp("-del", argv[i])) {
            cmd.deleteP = 1;
            continue;
        }

        if (0 == strcmp("-disk", argv[i])) {
            cmd.diskfftP = 1;
            continue;
        }

        if (0 == strcmp("-mem", argv[i])) {
            cmd.memfftP = 1;
            continue;
        }

        if (0 == strcmp("-tmpdir", argv[i])) {
            int keep = i;
            cmd.tmpdirP = 1;
            i = getStringOpt(argc, argv, i, &cmd.tmpdir, 1);
            cmd.tmpdirC = i - keep;
            continue;
        }

        if (0 == strcmp("-outdir", argv[i])) {
            int keep = i;
            cmd.outdirP = 1;
            i = getStringOpt(argc, argv, i, &cmd.outdir, 1);
            cmd.outdirC = i - keep;
            continue;
        }

        if (argv[i][0] == '-') {
            fprintf(stderr, "\n%s: unknown option `%s'\n\n",
                    Program, argv[i]);
            usage();
        }
        argv[cmd.argc++] = argv[i];
    }

    cmd.argv = argv + 1;
    cmd.argc -= 1;

    if (1 > cmd.argc) {
        fprintf(stderr,
                "%s: there should be at least 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    if (16384 < cmd.argc) {
        fprintf(stderr,
                "%s: there should be at most 16384 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    return &cmd;
}
