/****
  command line parser -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include <math.h>

#include "show_pfd_cmd.h"

char *Program;

static Cmdline cmd = {
    /***** -noxwin: Do not show the result plots on-screen, only make postscript files */
    /* noxwinP = */ 0,
    /***** -showfold: Use the input fold paramters (i.e. not the optimized values) when showing the plot */
    /* showfoldP = */ 0,
    /***** -scaleparts: Scale the part profiles independently */
    /* scalepartsP = */ 0,
    /***** -allgrey: Make all the images greyscale instead of color */
    /* allgreyP = */ 0,
    /***** -justprofs: Only output the profile portions of the plot */
    /* justprofsP = */ 0,
    /***** -portrait: Orient the output in portrait mode (for -justprofs) */
    /* portraitP = */ 0,
    /***** -events: The folded data were events instead of samples or bins */
    /* eventsP = */ 0,
    /***** -infoonly: Display the pfd info and exit without generating plots. */
    /* infoonlyP = */ 0,
    /***** -fixchi: Adjust the reduced chi^2 values so that off-pulse reduced chi^2 = 1 */
    /* fixchiP = */ 0,
    /***** -samples: Treat the data as samples and not as finite-duration integrated data */
    /* samplesP = */ 0,
    /***** -normalize: Normalize stats for each fold (i.e. to bandpass flatten subbands) */
    /* normalizeP = */ 0,
    /***** -killsubs: Comma separated string (no spaces!) of subbands to explicitly remove from analysis (i.e. zero out).  Ranges are specified by min:max[:step] */
    /* killsubsstrP = */ 0,
    /* killsubsstr = */ NULL,
    /* killsubsstrC = */ 0,
    /***** -killparts: Comma separated string (no spaces!) of intervals to explicitly remove from analysis (i.e. zero-out).  Ranges are specified by min:max[:step] */
    /* killpartsstrP = */ 0,
    /* killpartsstr = */ NULL,
    /* killpartsstrC = */ 0,
    /***** uninterpreted rest of command line */
    /* argc = */ 0,
    /* argv = */ NULL,
    /***** the original command line concatenated */
    /* full_cmd_line = */ NULL
};

/*********************************************************************/

int getStringOpt(int argc, char **argv, int i, char **value, int force)
{
    i += 1;
    if (i >= argc) {
        if (force) {
            fprintf(stderr, "%s: missing string after option `%s'\n",
                    Program, argv[i - 1]);
            exit(EXIT_FAILURE);
        }
        return i - 1;
    }

    if (!force && argv[i][0] == '-')
        return i - 1;
    *value = argv[i];
    return i;
}

/*********************************************************************/

static char *catArgv(int argc, char **argv)
{
    int i;
    size_t l, pos, n;
    char *s;

    for (i = 0, l = 1; i < argc; i++)
        l += strlen(argv[i]) + 1;
    s = (char *) malloc(l);
    if (!s) {
        fprintf(stderr, "%s: out of memory\n", Program);
        exit(EXIT_FAILURE);
    }
    for (i = 0, pos = 0; i < argc; i++) {
        n = strlen(argv[i]);
        if (i > 0)
            s[pos++] = ' ';
        memcpy(s + pos, argv[i], n);
        pos += n;
    }
    s[pos] = '\0';
    return s;
}

/*********************************************************************/

void showOptionValues(void)
{
    int i;

    printf("Full command line is:\n`%s'\n", cmd.full_cmd_line);

    /***** -noxwin: Do not show the result plots on-screen, only make postscript files */
    if (!cmd.noxwinP) {
        printf("-noxwin not found.\n");
    } else {
        printf("-noxwin found:\n");
    }

    /***** -showfold: Use the input fold paramters (i.e. not the optimized values) when showing the plot */
    if (!cmd.showfoldP) {
        printf("-showfold not found.\n");
    } else {
        printf("-showfold found:\n");
    }

    /***** -scaleparts: Scale the part profiles independently */
    if (!cmd.scalepartsP) {
        printf("-scaleparts not found.\n");
    } else {
        printf("-scaleparts found:\n");
    }

    /***** -allgrey: Make all the images greyscale instead of color */
    if (!cmd.allgreyP) {
        printf("-allgrey not found.\n");
    } else {
        printf("-allgrey found:\n");
    }

    /***** -justprofs: Only output the profile portions of the plot */
    if (!cmd.justprofsP) {
        printf("-justprofs not found.\n");
    } else {
        printf("-justprofs found:\n");
    }

    /***** -portrait: Orient the output in portrait mode (for -justprofs) */
    if (!cmd.portraitP) {
        printf("-portrait not found.\n");
    } else {
        printf("-portrait found:\n");
    }

    /***** -events: The folded data were events instead of samples or bins */
    if (!cmd.eventsP) {
        printf("-events not found.\n");
    } else {
        printf("-events found:\n");
    }

    /***** -infoonly: Display the pfd info and exit without generating plots. */
    if (!cmd.infoonlyP) {
        printf("-infoonly not found.\n");
    } else {
        printf("-infoonly found:\n");
    }

    /***** -fixchi: Adjust the reduced chi^2 values so that off-pulse reduced chi^2 = 1 */
    if (!cmd.fixchiP) {
        printf("-fixchi not found.\n");
    } else {
        printf("-fixchi found:\n");
    }

    /***** -samples: Treat the data as samples and not as finite-duration integrated data */
    if (!cmd.samplesP) {
        printf("-samples not found.\n");
    } else {
        printf("-samples found:\n");
    }

    /***** -normalize: Normalize stats for each fold (i.e. to bandpass flatten subbands) */
    if (!cmd.normalizeP) {
        printf("-normalize not found.\n");
    } else {
        printf("-normalize found:\n");
    }

    /***** -killsubs: Comma separated string (no spaces!) of subbands to explicitly remove from analysis (i.e. zero out).  Ranges are specified by min:max[:step] */
    if (!cmd.killsubsstrP) {
        printf("-killsubs not found.\n");
    } else {
        printf("-killsubs found:\n");
        if (!cmd.killsubsstrC) {
            printf("  no values\n");
        } else {
            printf("  value = `%s'\n", cmd.killsubsstr);
        }
    }

    /***** -killparts: Comma separated string (no spaces!) of intervals to explicitly remove from analysis (i.e. zero-out).  Ranges are specified by min:max[:step] */
    if (!cmd.killpartsstrP) {
        printf("-killparts not found.\n");
    } else {
        printf("-killparts found:\n");
        if (!cmd.killpartsstrC) {
            printf("  no values\n");
        } else {
            printf("  value = `%s'\n", cmd.killpartsstr);
        }
    }

    if (!cmd.argc) {
        printf("no remaining parameters in argv\n");
    } else {
        printf("argv =");
        for (i = 0; i < cmd.argc; i++)
            printf(" `%s'", cmd.argv[i]);
        printf("\n");
    }
}

/*********************************************************************/

void usage(void)
{
    fputs("   [-noxwin] [-showfold] [-scaleparts] [-allgrey] [-justprofs] [-portrait] [-events] [-infoonly] [-fixchi] [-samples] [-normalize] [-killsubs killsubsstr] [-killparts killpartsstr] [--] infile ...\n", stderr);
    fputs("      Displays or regenerates the Postscript for a 'pfd' file created by prepfold.\n", stderr);
    fputs("        -noxwin: Do not show the result plots on-screen, only make postscript files\n", stderr);
    fputs("      -showfold: Use the input fold paramters (i.e. not the optimized values) when showing the plot\n", stderr);
    fputs("    -scaleparts: Scale the part profiles independently\n", stderr);
    fputs("       -allgrey: Make all the images greyscale instead of color\n", stderr);
    fputs("     -justprofs: Only output the profile portions of the plot\n", stderr);
    fputs("      -portrait: Orient the output in portrait mode (for -justprofs)\n", stderr);
    fputs("        -events: The folded data were events instead of samples or bins\n", stderr);
    fputs("      -infoonly: Display the pfd info and exit without generating plots.\n", stderr);
    fputs("        -fixchi: Adjust the reduced chi^2 values so that off-pulse reduced chi^2 = 1\n", stderr);
    fputs("       -samples: Treat the data as samples and not as finite-duration integrated data\n", stderr);
    fputs("     -normalize: Normalize stats for each fold (i.e. to bandpass flatten subbands)\n", stderr);
    fputs("      -killsubs: Comma separated string (no spaces!) of subbands to explicitly remove from analysis (i.e. zero out).  Ranges are specified by min:max[:step]\n", stderr);
    fputs("                 1 char* value\n", stderr);
    fputs("     -killparts: Comma separated string (no spaces!) of intervals to explicitly remove from analysis (i.e. zero-out).  Ranges are specified by min:max[:step]\n", stderr);
    fputs("                 1 char* value\n", stderr);
    fputs("         infile: The input 'pfd' file name.\n", stderr);
    fputs("                 1...100 values\n", stderr);
    fputs("  CLI code generated: 03Jul26\n", stderr);
    fputs("  ", stderr);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

Cmdline *parseCmdline(int argc, char **argv)
{
    int i;

    Program = argv[0];
    cmd.full_cmd_line = catArgv(argc, argv);
    for (i = 1, cmd.argc = 1; i < argc; i++) {

        if (0 == strcmp("--", argv[i])) {
            while (++i < argc)
                argv[cmd.argc++] = argv[i];
            continue;
        }

        if (0 == strcmp("-noxwin", argv[i])) {
            cmd.noxwinP = 1;
            continue;
        }

        if (0 == strcmp("-showfold", argv[i])) {
            cmd.showfoldP = 1;
            continue;
        }

        if (0 == strcmp("-scaleparts", argv[i])) {
            cmd.scalepartsP = 1;
            continue;
        }

        if (0 == strcmp("-allgrey", argv[i])) {
            cmd.allgreyP = 1;
            continue;
        }

        if (0 == strcmp("-justprofs", argv[i])) {
            cmd.justprofsP = 1;
            continue;
        }

        if (0 == strcmp("-portrait", argv[i])) {
            cmd.portraitP = 1;
            continue;
        }

        if (0 == strcmp("-events", argv[i])) {
            cmd.eventsP = 1;
            continue;
        }

        if (0 == strcmp("-infoonly", argv[i])) {
            cmd.infoonlyP = 1;
            continue;
        }

        if (0 == strcmp("-fixchi", argv[i])) {
            cmd.fixchiP = 1;
            continue;
        }

        if (0 == strcmp("-samples", argv[i])) {
            cmd.samplesP = 1;
            continue;
        }

        if (0 == strcmp("-normalize", argv[i])) {
            cmd.normalizeP = 1;
            continue;
        }

        if (0 == strcmp("-killsubs", argv[i])) {
            int keep = i;
            cmd.killsubsstrP = 1;
            i = getStringOpt(argc, argv, i, &cmd.killsubsstr, 1);
            cmd.killsubsstrC = i - keep;
            continue;
        }

        if (0 == strcmp("-killparts", argv[i])) {
            int keep = i;
            cmd.killpartsstrP = 1;
            i = getStringOpt(argc, argv, i, &cmd.killpartsstr, 1);
            cmd.killpartsstrC = i - keep;
            continue;
        }

        if (argv[i][0] == '-') {
            fprintf(stderr, "\n%s: unknown option `%s'\n\n",
                    Program, argv[i]);
            usage();
        }
        argv[cmd.argc++] = argv[i];
    }

    cmd.argv = argv + 1;
    cmd.argc -= 1;

    if (1 > cmd.argc) {
        fprintf(stderr,
                "%s: there should be at least 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    if (100 < cmd.argc) {
        fprintf(stderr,
                "%s: there should be at most 100 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    return &cmd;
}
