/****
  command line parser -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include <math.h>

#include "toas2dat_cmd.h"

char *Program;

static Cmdline cmd = {
    /***** -n: The number of bins in the output time series */
    /* numoutP = */ 0,
    /* numout = */ 0,
    /* numoutC = */ 0,
    /***** -dt: Time interval in seconds for output time bins */
    /* dtP = */ 0,
    /* dt = */ 0,
    /* dtC = */ 0,
    /***** -t0: Time for the start of bin 0 (same units as the TOAs) */
    /* t0P = */ 0,
    /* t0 = */ 0,
    /* t0C = */ 0,
    /***** -o: Name of the output time series file */
    /* outfileP = */ 0,
    /* outfile = */ NULL,
    /* outfileC = */ 0,
    /***** -text: TOAs are ASCII text (default is binary double) */
    /* textP = */ 0,
    /***** -float: TOAs are binary floats (default is binary double) */
    /* floatP = */ 0,
    /***** -sec: TOA unit is seconds (default is days) */
    /* secP = */ 0,
    /***** uninterpreted rest of command line */
    /* argc = */ 0,
    /* argv = */ NULL,
    /***** the original command line concatenated */
    /* full_cmd_line = */ NULL
};

/*********************************************************************/

int getLongOpt(int argc, char **argv, int i, long *value, int force)
{
    char *end;

    if (++i >= argc)
        goto nothingFound;

    errno = 0;
    *value = strtol(argv[i], &end, 0);

    if (end == argv[i])
        goto nothingFound;

    while (isspace((unsigned char) *end))
        end++;
    if (*end)
        goto nothingFound;

    if (errno == ERANGE) {
        fprintf(stderr,
                "%s: parameter `%s' of option `%s' too large to represent\n",
                Program, argv[i], argv[i - 1]);
        exit(EXIT_FAILURE);
    }
    return i;

  nothingFound:
    if (!force)
        return i - 1;
    fprintf(stderr,
            "%s: missing or malformed value after option `%s'\n",
            Program, argv[i - 1]);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

int getDoubleOpt(int argc, char **argv, int i, double *value, int force)
{
    char *end;

    if (++i >= argc)
        goto nothingFound;

    errno = 0;
    *value = strtod(argv[i], &end);

    if (end == argv[i])
        goto nothingFound;

    while (isspace((unsigned char) *end))
        end++;
    if (*end)
        goto nothingFound;

    if (errno == ERANGE) {
        fprintf(stderr,
                "%s: parameter `%s' of option `%s' too %s to represent\n",
                Program, argv[i], argv[i - 1], (*value == 0.0 ? "small" : "large"));
        exit(EXIT_FAILURE);
    }
    return i;

  nothingFound:
    if (!force)
        return i - 1;
    fprintf(stderr,
            "%s: missing or malformed value after option `%s'\n",
            Program, argv[i - 1]);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

int getStringOpt(int argc, char **argv, int i, char **value, int force)
{
    i += 1;
    if (i >= argc) {
        if (force) {
            fprintf(stderr, "%s: missing string after option `%s'\n",
                    Program, argv[i - 1]);
            exit(EXIT_FAILURE);
        }
        return i - 1;
    }

    if (!force && argv[i][0] == '-')
        return i - 1;
    *value = argv[i];
    return i;
}

/*********************************************************************/

void checkLongLower(const char *opt, long *values, int count, long max)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] <= max)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' greater than max=%ld\n",
                Program, i + 1, opt, max);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

void checkLongHigher(const char *opt, long *values, int count, long min)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] >= min)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' smaller than min=%ld\n",
                Program, i + 1, opt, min);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

void checkDoubleLower(const char *opt, double *values, int count, double max)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] <= max)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' greater than max=%f\n",
                Program, i + 1, opt, max);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

void checkDoubleHigher(const char *opt, double *values, int count, double min)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] >= min)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' smaller than min=%f\n",
                Program, i + 1, opt, min);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

static void missingErr(const char *opt)
{
    fprintf(stderr, "%s: mandatory option `%s' missing\n", Program, opt);
}

/*********************************************************************/

static char *catArgv(int argc, char **argv)
{
    int i;
    size_t l, pos, n;
    char *s;

    for (i = 0, l = 1; i < argc; i++)
        l += strlen(argv[i]) + 1;
    s = (char *) malloc(l);
    if (!s) {
        fprintf(stderr, "%s: out of memory\n", Program);
        exit(EXIT_FAILURE);
    }
    for (i = 0, pos = 0; i < argc; i++) {
        n = strlen(argv[i]);
        if (i > 0)
            s[pos++] = ' ';
        memcpy(s + pos, argv[i], n);
        pos += n;
    }
    s[pos] = '\0';
    return s;
}

/*********************************************************************/

void showOptionValues(void)
{
    int i;

    printf("Full command line is:\n`%s'\n", cmd.full_cmd_line);

    /***** -n: The number of bins in the output time series */
    if (!cmd.numoutP) {
        printf("-n not found.\n");
    } else {
        printf("-n found:\n");
        if (!cmd.numoutC) {
            printf("  no values\n");
        } else {
            printf("  value = `%ld'\n", cmd.numout);
        }
    }

    /***** -dt: Time interval in seconds for output time bins */
    if (!cmd.dtP) {
        printf("-dt not found.\n");
    } else {
        printf("-dt found:\n");
        if (!cmd.dtC) {
            printf("  no values\n");
        } else {
            printf("  value = `%.40g'\n", cmd.dt);
        }
    }

    /***** -t0: Time for the start of bin 0 (same units as the TOAs) */
    if (!cmd.t0P) {
        printf("-t0 not found.\n");
    } else {
        printf("-t0 found:\n");
        if (!cmd.t0C) {
            printf("  no values\n");
        } else {
            printf("  value = `%.40g'\n", cmd.t0);
        }
    }

    /***** -o: Name of the output time series file */
    if (!cmd.outfileP) {
        printf("-o not found.\n");
    } else {
        printf("-o found:\n");
        if (!cmd.outfileC) {
            printf("  no values\n");
        } else {
            printf("  value = `%s'\n", cmd.outfile);
        }
    }

    /***** -text: TOAs are ASCII text (default is binary double) */
    if (!cmd.textP) {
        printf("-text not found.\n");
    } else {
        printf("-text found:\n");
    }

    /***** -float: TOAs are binary floats (default is binary double) */
    if (!cmd.floatP) {
        printf("-float not found.\n");
    } else {
        printf("-float found:\n");
    }

    /***** -sec: TOA unit is seconds (default is days) */
    if (!cmd.secP) {
        printf("-sec not found.\n");
    } else {
        printf("-sec found:\n");
    }

    if (!cmd.argc) {
        printf("no remaining parameters in argv\n");
    } else {
        printf("argv =");
        for (i = 0; i < cmd.argc; i++)
            printf(" `%s'", cmd.argv[i]);
        printf("\n");
    }
}

/*********************************************************************/

void usage(void)
{
    fputs("   -n numout -dt dt [-t0 t0] -o outfile [-text] [-float] [-sec] [--] file\n", stderr);
    fputs("      Converts TOAs into a binned time series.\n", stderr);
    fputs("        -n: The number of bins in the output time series\n", stderr);
    fputs("            1 long value between 0 and oo\n", stderr);
    fputs("       -dt: Time interval in seconds for output time bins\n", stderr);
    fputs("            1 double value between 0 and oo\n", stderr);
    fputs("       -t0: Time for the start of bin 0 (same units as the TOAs)\n", stderr);
    fputs("            1 double value\n", stderr);
    fputs("        -o: Name of the output time series file\n", stderr);
    fputs("            1 char* value\n", stderr);
    fputs("     -text: TOAs are ASCII text (default is binary double)\n", stderr);
    fputs("    -float: TOAs are binary floats (default is binary double)\n", stderr);
    fputs("      -sec: TOA unit is seconds (default is days)\n", stderr);
    fputs("      file: Input TOA file name\n", stderr);
    fputs("            1 value\n", stderr);
    fputs("  CLI code generated: 03Jul26\n", stderr);
    fputs("  ", stderr);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

Cmdline *parseCmdline(int argc, char **argv)
{
    int i;
    int missingMandatory = 0;

    Program = argv[0];
    cmd.full_cmd_line = catArgv(argc, argv);
    for (i = 1, cmd.argc = 1; i < argc; i++) {

        if (0 == strcmp("--", argv[i])) {
            while (++i < argc)
                argv[cmd.argc++] = argv[i];
            continue;
        }

        if (0 == strcmp("-n", argv[i])) {
            int keep = i;
            cmd.numoutP = 1;
            i = getLongOpt(argc, argv, i, &cmd.numout, 1);
            cmd.numoutC = i - keep;
            checkLongHigher("-n", &cmd.numout, cmd.numoutC, 0);
            continue;
        }

        if (0 == strcmp("-dt", argv[i])) {
            int keep = i;
            cmd.dtP = 1;
            i = getDoubleOpt(argc, argv, i, &cmd.dt, 1);
            cmd.dtC = i - keep;
            checkDoubleHigher("-dt", &cmd.dt, cmd.dtC, 0);
            continue;
        }

        if (0 == strcmp("-t0", argv[i])) {
            int keep = i;
            cmd.t0P = 1;
            i = getDoubleOpt(argc, argv, i, &cmd.t0, 1);
            cmd.t0C = i - keep;
            continue;
        }

        if (0 == strcmp("-o", argv[i])) {
            int keep = i;
            cmd.outfileP = 1;
            i = getStringOpt(argc, argv, i, &cmd.outfile, 1);
            cmd.outfileC = i - keep;
            continue;
        }

        if (0 == strcmp("-text", argv[i])) {
            cmd.textP = 1;
            continue;
        }

        if (0 == strcmp("-float", argv[i])) {
            cmd.floatP = 1;
            continue;
        }

        if (0 == strcmp("-sec", argv[i])) {
            cmd.secP = 1;
            continue;
        }

        if (argv[i][0] == '-') {
            fprintf(stderr, "\n%s: unknown option `%s'\n\n",
                    Program, argv[i]);
            usage();
        }
        argv[cmd.argc++] = argv[i];
    }

    if (!cmd.numoutP) {
        missingErr("-n");
        missingMandatory = 1;
    }
    if (!cmd.dtP) {
        missingErr("-dt");
        missingMandatory = 1;
    }
    if (!cmd.outfileP) {
        missingErr("-o");
        missingMandatory = 1;
    }
    if (missingMandatory)
        exit(EXIT_FAILURE);

    cmd.argv = argv + 1;
    cmd.argc -= 1;

    if (1 > cmd.argc) {
        fprintf(stderr,
                "%s: there should be at least 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    if (1 < cmd.argc) {
        fprintf(stderr,
                "%s: there should be at most 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    return &cmd;
}
